[build]
  command = "npm run build"
  functions = "dist/functions"
  publish = "dist"

[dev]
  port = 8888
  autoLaunch = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200